<a href="https://colab.research.google.com/github/workwithHasnain/MLS24/blob/main/AssignmentOne_Hasnain.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron, LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.neural_network import MLPClassifier

In [ ]:
# Reading CSV
data = pd.read_csv('diabetes.csv')

In [ ]:
# Separate features (X) and target variable (y)
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

In [ ]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify = y)

In [ ]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
# Initialize models
perceptron = Perceptron(eta0=0.1, random_state=42)
adaline = MLPClassifier(hidden_layer_sizes=(1,), activation='identity', solver='sgd', random_state=42)
logistic_regression = LogisticRegression(random_state=42)

In [ ]:
# Fit the models
perceptron.fit(X_train, y_train)
adaline.fit(X_train, y_train)
logistic_regression.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


LogisticRegression(random_state=42)

In [ ]:
# Make predictions
y_pred_perceptron = perceptron.predict(X_test)
y_pred_adaline = adaline.predict(X_test)
y_pred_logistic_regression = logistic_regression.predict(X_test)

In [ ]:
# Calculate accuracy
accuracy_perceptron = accuracy_score(y_test, y_pred_perceptron)
accuracy_adaline = accuracy_score(y_test, y_pred_adaline)
accuracy_logistic_regression = accuracy_score(y_test, y_pred_logistic_regression)

In [ ]:
# Display accuracy for each algorithm
print("Accuracy for Perceptron:", accuracy_perceptron)
print("Accuracy for Adaline:", accuracy_adaline)
print("Accuracy for Logistic Regression:", accuracy_logistic_regression)

# Display confusion matrix for each algorithm
print("\nConfusion Matrix for Perceptron:")
print(confusion_matrix(y_test, y_pred_perceptron))
print("\nConfusion Matrix for Adaline:")
print(confusion_matrix(y_test, y_pred_adaline))
print("\nConfusion Matrix for Logistic Regression:")
print(confusion_matrix(y_test, y_pred_logistic_regression))

# Display classification report for each algorithm
print("\nClassification Report for Perceptron:")
print(classification_report(y_test, y_pred_perceptron))
print("\nClassification Report for Adaline:")
print(classification_report(y_test, y_pred_adaline))
print("\nClassification Report for Logistic Regression:")
print(classification_report(y_test, y_pred_logistic_regression))

Accuracy for Perceptron: 0.7272727272727273
Accuracy for Adaline: 0.7207792207792207
Accuracy for Logistic Regression: 0.7142857142857143

Confusion Matrix for Perceptron:
[[80 20]
 [22 32]]

Confusion Matrix for Adaline:
[[83 17]
 [26 28]]

Confusion Matrix for Logistic Regression:
[[82 18]
 [26 28]]

Classification Report for Perceptron:
              precision    recall  f1-score   support

           0       0.78      0.80      0.79       100
           1       0.62      0.59      0.60        54

    accuracy                           0.73       154
   macro avg       0.70      0.70      0.70       154
weighted avg       0.73      0.73      0.73       154


Classification Report for Adaline:
              precision    recall  f1-score   support

           0       0.76      0.83      0.79       100
           1       0.62      0.52      0.57        54

    accuracy                           0.72       154
   macro avg       0.69      0.67      0.68       154
weighted avg       0.71

The Perceptron is giving the highest accuracy from the rest.

Confusion Matrix and Classification Reports are displayed above.